# Generated by Django 5.0.3 on 2024-03-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=98),
        ),
    ]
